// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8jJmBmsbuLhHg9zHphzfDqrZO9AV2tJc',
    appId: '1:574152725785:web:9d2319fdb9c3da3fb4a188',
    messagingSenderId: '574152725785',
    projectId: 'dddm-scada',
    authDomain: 'dddm-scada.firebaseapp.com',
    storageBucket: 'dddm-scada.appspot.com',
    measurementId: 'G-4BRW4PX5DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwdlTuBNACsWhlxSkp_6qGrpVP-tyRDp0',
    appId: '1:574152725785:android:752fc8aa76bf04b2b4a188',
    messagingSenderId: '574152725785',
    projectId: 'dddm-scada',
    storageBucket: 'dddm-scada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWNCu4F-guEARkQWEZ2egri2SVEtJpug',
    appId: '1:574152725785:ios:c9eb4d4ce29af1eeb4a188',
    messagingSenderId: '574152725785',
    projectId: 'dddm-scada',
    storageBucket: 'dddm-scada.appspot.com',
    iosBundleId: 'com.example.scadaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDWNCu4F-guEARkQWEZ2egri2SVEtJpug',
    appId: '1:574152725785:ios:c9eb4d4ce29af1eeb4a188',
    messagingSenderId: '574152725785',
    projectId: 'dddm-scada',
    storageBucket: 'dddm-scada.appspot.com',
    iosBundleId: 'com.example.scadaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8jJmBmsbuLhHg9zHphzfDqrZO9AV2tJc',
    appId: '1:574152725785:web:7370a237caaac061b4a188',
    messagingSenderId: '574152725785',
    projectId: 'dddm-scada',
    authDomain: 'dddm-scada.firebaseapp.com',
    storageBucket: 'dddm-scada.appspot.com',
    measurementId: 'G-DLBDJBLW3P',
  );
}
